### PR TITLE
Fixed cmake not respecting cxxflags

### PR DESCRIPTION
**Pull request by Mailaender**
via http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/games-arcade/jvgs/files/jvgs-0.5-flags.patch?view=markup

### CODE REVIEW

**Comment by jaspervdj** [comment]
Thanks! Do you want me to create a new release?

**Comment by Mailaender** [comment]
Dunno. This is already patched in Gentoo by @hasufell.

I packaged it myself https://build.opensuse.org/request/show/260349 but it still won't run.

```
/usr/lib/jvgs: error while loading shared libraries: liblua.so: cannot open shared object file: No such file or directory
```

**Comment by hasufell** [comment]
This is a very old patch and works well in the gentoo environment where users don't set 'CMAKE_CXX_FLAGS' via e.g. ccmake.

The better solution is probably

```
SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTIXML_USE_STL" )
```

and should work for all use cases.

**Comment by Mailaender** [comment]
Should have been `SET( CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DTIXML_USE_STL" )` then probably.

**Pull request merged**
